In [1]:
# Check venv matches:
# C:\Users\mitch\source\repos\mtg_ai\.venv\Scripts\python.exe
import sys
print(sys.executable)

C:\Users\mitch\source\repos\mtg_ai\.venv\Scripts\python.exe

In [2]:
# imports
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import numpy as np

# Make pandas usable for wide MTG data
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 120)
pd.set_option("display.width", 0)

In [3]:
# confirm path to data
PROJECT_ROOT = Path("../..").resolve()
print(PROJECT_ROOT)
DATA_DIR = PROJECT_ROOT / "data" / "raw"
CARDS_RAW_PATH = DATA_DIR / "all_cards_20260503T212553.455+0000.json"
print(CARDS_RAW_PATH)

# Load parquet to dataframe
cards_raw = pd.read_json(CARDS_RAW_PATH)
# Basic shape and schema
print(cards_raw.shape)
cards_raw.head(5)

C:\Users\mitch\source\repos\mtg_ai
C:\Users\mitch\source\repos\mtg_ai\data\raw\all_cards_20260503T212553.455+0000.json
(529942, 88)

,object,id,oracle_id,multiverse_ids,mtgo_id,arena_id,tcgplayer_id,cardmarket_id,name,lang,released_at,uri,scryfall_uri,layout,highres_image,image_status,image_uris,mana_cost,cmc,type_line,oracle_text,colors,color_identity,keywords,produced_mana,all_parts,legalities,games,reserved,game_changer,foil,nonfoil,finishes,oversized,promo,reprint,variation,set_id,set,set_name,set_type,set_uri,set_search_uri,scryfall_set_uri,rulings_uri,prints_search_uri,collector_number,digital,rarity,card_back_id,artist,artist_ids,illustration_id,border_color,frame,full_art,textless,booster,story_spotlight,prices,related_uris,purchase_uris,mtgo_foil_id,power,toughness,flavor_text,edhrec_rank,penny_rank,printed_name,printed_type_line,printed_text,security_stamp,promo_types,loyalty,watermark,frame_effects,card_faces,preview,resource_id,color_indicator,tcgplayer_etched_id,content_warning,flavor_name,attraction_lights,variation_of,life_modifier,hand_modifier,defense
0,card,0000419b-0bba-4488-8f7a-6194544ce91e,b34bb2dc-c1af-4d77-b0b3-a0fb342a5fc6,[668564],129825.0,91829.0,558404.0,777725.0,Forest,en,2024-08-02,https://api.scryfall.com/cards/0000419b-0bba-4488-8f7a-6194544ce91e,https://scryfall.com/card/blb/280/forest?utm_source=api,normal,True,highres_scan,"{'small': 'https://cards.scryfall.io/small/front/0/0/0000419b-0bba-4488-8f7a-6194544ce91e.jpg?1721427487', 'normal':...",,0.0,Basic Land — Forest,({T}: Add {G}.),[],[G],[],[G],"[{'object': 'related_card', 'id': 'bddc66f7-4e94-4857-ba7d-6b0083d0bfa0', 'component': 'combo_piece', 'name': 'Fores...","{'standard': 'legal', 'future': 'legal', 'historic': 'legal', 'timeless': 'legal', 'gladiator': 'legal', 'pioneer': ...","[paper, mtgo, arena]",False,False,True,True,"[nonfoil, foil]",False,False,True,False,a2f58272-bba6-439d-871e-7a46686ac018,blb,Bloomburrow,expansion,https://api.scryfall.com/sets/a2f58272-bba6-439d-871e-7a46686ac018,https://api.scryfall.com/cards/search?order=set&q=e%3Ablb&unique=prints,https://scryfall.com/sets/blb?utm_source=api,https://api.scryfall.com/cards/0000419b-0bba-4488-8f7a-6194544ce91e/rulings,https://api.scryfall.com/cards/search?order=released&q=oracleid%3Ab34bb2dc-c1af-4d77-b0b3-a0fb342a5fc6&unique=prints,280,False,common,0aeebaf5-8c7d-4636-9e82-8c27447861f7,David Robert Hovey,[22ab27e3-6476-48f1-a9f7-9a9e86339030],fb2b1ca2-7440-48c2-81c8-84da0a45a626,black,2015,True,False,True,False,"{'usd': '0.31', 'usd_foil': '0.41', 'usd_etched': None, 'eur': '0.26', 'eur_foil': '0.55', 'tix': '0.03'}","{'gatherer': 'https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=668564&printed=false', 'tcgplayer_in...",{'tcgplayer': 'https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2F...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,card,0000579f-7b35-4ed3-b44c-db2a538066fe,44623693-51d6-49ad-8cd7-140505caf02f,[109722],25527.0,NaN,14240.0,13850.0,Fury Sliver,en,2006-10-06,https://api.scryfall.com/cards/0000579f-7b35-4ed3-b44c-db2a538066fe,https://scryfall.com/card/tsp/157/fury-sliver?utm_source=api,normal,True,highres_scan,"{'small': 'https://cards.scryfall.io/small/front/0/0/0000579f-7b35-4ed3-b44c-db2a538066fe.jpg?1562894979', 'normal':...",{5}{R},6.0,Creature — Sliver,All Sliver creatures have double strike.,[R],[R],[],NaN,NaN,"{'standard': 'not_legal', 'future': 'not_legal', 'historic': 'not_legal', 'timeless': 'not_legal', 'gladiator': 'not...","[paper, mtgo]",False,False,True,True,"[nonfoil, foil]",False,False,False,False,c1d109bc-ffd8-428f-8d7d-3f8d7e648046,tsp,Time Spiral,expansion,https://api.scryfall.com/sets/c1d109bc-ffd8-428f-8d7d-3f8d7e648046,https://api.scryfall.com/cards/search?order=set&q=e%3Atsp&unique=prints,https://scryfall.com/sets/tsp?utm_source=api,https://api.scryfall.com/cards/0000579f-7b35-4ed3-b44c-db2a538066fe/rulings,https://api.scryfall.com/cards/search?order=released&q=oracleid%3A44623693-51d6-49ad-8cd7-140505caf02f&unique=prints,157,False,uncommon,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Paolo Parente,[d48dd097-720d-476a-8722-6a02854ae28b],2fcca987-364c-4738-a75b-099d8a26d614,black,2003,False,False,True,False,"{'usd': '0.54', 'usd_foil': '2.85', 'usd_etched': None, 'eur': '0.13', 'eur_foil': '1.28', 'tix': '0.03'}","{'gatherer': 'https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=109722&printed=false', 'tcgplayer_in...",{'tcgplayer': 'https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2F...,25528.0,3,3,"""A rift opened, and our arrows were abruptly stilled. To move was to push the world. But the sliver's claw still twi...",9962.0,11877.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,card,00006596-1166-4a79-8443-ca9f82e6db4e,8ae3562f-28b7-4462-96ed-be0cf7052ccc,[189637],34586.0,NaN,33347.0,21851.0,Kor Outfitter,en,2009-10-02,https://api.scryfall.com/cards/00006596-1166-4a79-8443-ca9f82e6db4e,https://scryfall.com/card/zen/21/kor-outfitter?utm_source=api,normal,True,highres_scan,"{'small': 'https://cards.scryfall.io/small/front/0/0/00006596-1166-4a79-8443-ca9f82e6db4e.jpg?1562609251', 'normal':...",{W}{W},2.0,Creature — Kor Soldier,"When this creature enters, you may attach target Equipment you control to target creature you control.",[W],[W],[],NaN,NaN,"{'standard': 'not_legal', 'future': 'not_legal', 'historic': 'not_legal', 'timeless': 'not_legal', 'gladiator': 'not...","[paper, mtgo]",False,False,True,True,"[nonfoil, foil]",False,False,False,False,eb16a2bd-a218-4e4e-8339-4aa1afc0c8d2,zen,Zendikar,expansion,https://api.scryfall.com/sets/eb16a2bd-a218-4e4e-8339-4aa1afc0c8d2,https://api.scryfall.com/cards/search?order=set&q=e%3Azen&unique=prints,https://scryfall.com/sets/zen?utm_source=api,https://api.scryfall.com/cards/00006596-1166-4a79-8443-ca9f82e6db4e/rulings,https://api.scryfall.com/cards/search?order=released&q=oracleid%3A8ae3562f-28b7-4462-96ed-be0cf7052ccc&unique=prints,21,False,common,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Kieran Yanner,[aa7e89ed-d294-4633-9057-ce04dacfcfa4],de0310d1-e97f-46e0-bc16-c980c2adedee,black,2003,False,False,True,False,"{'usd': '0.18', 'usd_foil': '1.73', 'usd_etched': None, 'eur': '0.29', 'eur_foil': '2.01', 'tix': '0.03'}","{'gatherer': 'https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=189637&printed=false', 'tcgplayer_in...",{'tcgplayer': 'https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2F...,34587.0,2,2,"""We take only what we need to survive. Believe me, you will need this.""",20285.0,5962.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,card,00009878-d086-46f0-a964-15734d8368ac,30cd69a8-7893-4075-94ca-04450ff821d3,[433932],NaN,NaN,NaN,NaN,Spirit of the Hearth,fr,2017-08-25,https://api.scryfall.com/cards/00009878-d086-46f0-a964-15734d8368ac,https://scryfall.com/card/c17/73/fr/esprit-du-foyer-(spirit-of-the-hearth)?utm_source=api,normal,False,lowres,"{'small': 'https://cards.scryfall.io/small/front/0/0/00009878-d086-46f0-a964-15734d8368ac.jpg?1562597860', 'normal':...",{4}{W}{W},6.0,Creature — Cat Spirit,Flying\nYou have hexproof. (You can't be the target of spells or abilities your opponents control.),[W],[W],[Flying],NaN,NaN,"{'standard': 'not_legal', 'future': 'not_legal', 'historic': 'not_legal', 'timeless': 'not_legal', 'gladiator': 'not...",[paper],False,False,False,True,[nonfoil],False,False,True,False,5caec427-0c78-4c37-b4ec-30f7e0ba9abf,c17,Commander 2017,commander,https://api.scryfall.com/sets/5caec427-0c78-4c37-b4ec-30f7e0ba9abf,https://api.scryfall.com/cards/search?order=set&q=e%3Ac17&unique=prints,https://scryfall.com/sets/c17?utm_source=api,https://api.scryfall.com/cards/00009878-d086-46f0-a964-15734d8368ac/rulings,https://api.scryfall.com/cards/search?order=released&q=oracleid%3A30cd69a8-7893-4075-94ca-04450ff821d3&unique=prints,73,False,rare,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Jason Chan,[8062d5a9-51b6-4822-933f-fa9e9dba8416],e8a09f86-98f6-46df-bf53-46a9f4117f36,black,2015,False,False,False,False,"{'usd': None, 'usd_foil': None, 'usd_etched': None, 'eur': None, 'eur_foil': None, 'tix': None}","{'gatherer': 'https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=433932&printed=true', 'tcgplayer_inf...",{'tcgplayer': 'https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2F...,NaN,4,5,"Les voleurs savent qu'un grognement dans la nuit signifie, « Allez cambrioler autre part. »",15512.0,14718.0,Esprit du foyer,Créature : chat et esprit,Vol\nVous avez la défense talismanique. (Vous ne pouvez pas être la cible de sorts ou de capacités que vos adversair...,oval,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,card,0000a54c-a511-4925-92dc-01b937f9afad,dc4e2134-f0c2-49aa-9ea3-ebf83af1445c,[],NaN,NaN,98659.0,282862.0,Spirit,en,2015-05-22,https://api.scryfall.com/cards/0000a54c-a511-4925-92dc-01b937f9afad,https://scryfall.com/card/tmm2/5/spirit?utm_source=api,token,True,highres_scan,"{'small': 'https://cards.scryfall.io/small/front/0/0/0000a54c-a511-4925-92dc-01b937f9afad.jpg?1562701869', 'normal':...",,0.0,Token Creature — Spirit,Flying,[W],[W],[Flying],NaN,"[{'object': 'related_card', 'id': '9e371a29-bb06-402d-8ea3-f2a0b982a310', 'component': 'combo_piece', 'name': 'Kykar...","{'standard': 'not_legal', 'future': 'not_legal', 'historic': 'not_legal', 'timeless': 'not_legal', 'gladiator': 'not...",[paper],False,False,False,True,[nonfoil],False,False,True,False,f7aa47c6-c1e2-4de5-9a68-4406d84bd6bb,tmm2,Modern Masters 2015 Tokens,token,https://api.scryfall.com/sets/f7aa47c6-c1e2-4de5-9a68-4406d84bd6bb,https://api.scryfall.com/cards/search?order=set&q=e%3Atmm2&unique=prints,https://scryfall.com/sets/tmm2?utm_source=api,https://api.scryfall.com/cards/0000a54c-a511-4925-92dc-01b937f9afad/rulings,https://api.scryfall.com/cards/search?order=released&q=oracleid%3Adc4e2134-f0c2-49aa-9ea3-ebf83af1445c&unique=prints,5,False,common,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Mike Sass,[155bc2cb-038d-4b1f-9990-6178db1d1a21],1dbe0618-dd47-442c-acf6-ac5e4b136e5a,black,2015,False,False,True,False,"{'usd': '0.09', 'usd_foil': None, 'usd_etched': None, 'eur': '0.06', 'eur_foil': None, 'tix': None}",{'tcgplayer_infinite_articles': 'https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer....,{'tcgplayer': 'https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2F...,NaN,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,[setpromo],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
cards_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 529942 entries, 0 to 529941
Data columns (total 88 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   object               529942 non-null  object
 1   id                   529942 non-null  object
 2   oracle_id            529861 non-null  object
 3   multiverse_ids       529942 non-null  object
 4   mtgo_id              60146 non-null   float64
 5   arena_id             16497 non-null   float64
 6   tcgplayer_id         98396 non-null   float64
 7   cardmarket_id        99639 non-null   float64
 8   name                 529942 non-null  object
 9   lang                 529942 non-null  object
 10  released_at          529942 non-null  datetime64[ns]
 11  uri                  529942 non-null  object
 12  scryfall_uri         529942 non-null  object
 13  layout               529942 non-null  object
 14  highres_image        529942 non-null  bool
 15  image_status         529942 non-null  object
 16  image_uris           521776 non-null  object
 17  mana_cost            521776 non-null  object
 18  cmc                  529861 non-null  float64
 19  type_line            529861 non-null  object
 20  oracle_text          518311 non-null  object
 21  colors               521776 non-null  object
 22  color_identity       529942 non-null  object
 23  keywords             529942 non-null  object
 24  produced_mana        78820 non-null   object
 25  all_parts            26508 non-null   object
 26  legalities           529942 non-null  object
 27  games                529942 non-null  object
 28  reserved             529942 non-null  bool
 29  game_changer         529942 non-null  bool
 30  foil                 529942 non-null  bool
 31  nonfoil              529942 non-null  bool
 32  finishes             529942 non-null  object
 33  oversized            529942 non-null  bool
 34  promo                529942 non-null  bool
 35  reprint              529942 non-null  bool
 36  variation            529942 non-null  bool
 37  set_id               529942 non-null  object
 38  set                  529942 non-null  object
 39  set_name             529942 non-null  object
 40  set_type             529942 non-null  object
 41  set_uri              529942 non-null  object
 42  set_search_uri       529942 non-null  object
 43  scryfall_set_uri     529942 non-null  object
 44  rulings_uri          529942 non-null  object
 45  prints_search_uri    529942 non-null  object
 46  collector_number     529942 non-null  object
 47  digital              529942 non-null  bool
 48  rarity               529942 non-null  object
 49  card_back_id         521776 non-null  object
 50  artist               529942 non-null  object
 51  artist_ids           529095 non-null  object
 52  illustration_id      521064 non-null  object
 53  border_color         529942 non-null  object
 54  frame                529942 non-null  object
 55  full_art             529942 non-null  bool
 56  textless             529942 non-null  bool
 57  booster              529942 non-null  bool
 58  story_spotlight      529942 non-null  bool
 59  prices               529942 non-null  object
 60  related_uris         529942 non-null  object
 61  purchase_uris        526214 non-null  object
 62  mtgo_foil_id         24341 non-null   float64
 63  power                256927 non-null  object
 64  toughness            256927 non-null  object
 65  flavor_text          266133 non-null  object
 66  edhrec_rank          498732 non-null  float64
 67  penny_rank           336137 non-null  float64
 68  printed_name         397905 non-null  object
 69  printed_type_line    346089 non-null  object
 70  printed_text         347461 non-null  object
 71  security_stamp       159946 non-null  object
 72  promo_types          88015 non-null   object
 73  loyalty              5807 non-null    object
 74  watermark            36386 non-null   object
 75  frame_effects        68967 non-null   object
 76  card_faces           11631 non-null   object
 77  preview              16579 non-null   object
 78  resource_id          22143 non-null   object
 79  color_indicator      544 non-null     object
 80  tcgplayer_etched_id  1225 non-null    float64
 81  content_warning      91 non-null      float64
 82  flavor_name          594 non-null     object
 83  attraction_lights    135 non-null     object
 84  variation_of         120 non-null     object
 85  life_modifier        119 non-null     float64
 86  hand_modifier        119 non-null     float64
 87  defense              1 non-null       float64
dtypes: bool(14), datetime64[ns](1), float64(13), object(60)
memory usage: 306.3+ MB

In [5]:
column_names = cards_raw.columns.tolist()
for name in column_names:
    print(name)

object
id
oracle_id
multiverse_ids
mtgo_id
arena_id
tcgplayer_id
cardmarket_id
name
lang
released_at
uri
scryfall_uri
layout
highres_image
image_status
image_uris
mana_cost
cmc
type_line
oracle_text
colors
color_identity
keywords
produced_mana
all_parts
legalities
games
reserved
game_changer
foil
nonfoil
finishes
oversized
promo
reprint
variation
set_id
set
set_name
set_type
set_uri
set_search_uri
scryfall_set_uri
rulings_uri
prints_search_uri
collector_number
digital
rarity
card_back_id
artist
artist_ids
illustration_id
border_color
frame
full_art
textless
booster
story_spotlight
prices
related_uris
purchase_uris
mtgo_foil_id
power
toughness
flavor_text
edhrec_rank
penny_rank
printed_name
printed_type_line
printed_text
security_stamp
promo_types
loyalty
watermark
frame_effects
card_faces
preview
resource_id
color_indicator
tcgplayer_etched_id
content_warning
flavor_name
attraction_lights
variation_of
life_modifier
hand_modifier
defense

In [6]:
cards_raw.loc[cards_raw["name"] == "Counterspell"]

,object,id,oracle_id,multiverse_ids,mtgo_id,arena_id,tcgplayer_id,cardmarket_id,name,lang,released_at,uri,scryfall_uri,layout,highres_image,image_status,image_uris,mana_cost,cmc,type_line,oracle_text,colors,color_identity,keywords,produced_mana,all_parts,legalities,games,reserved,game_changer,foil,nonfoil,finishes,oversized,promo,reprint,variation,set_id,set,set_name,set_type,set_uri,set_search_uri,scryfall_set_uri,rulings_uri,prints_search_uri,collector_number,digital,rarity,card_back_id,artist,artist_ids,illustration_id,border_color,frame,full_art,textless,booster,story_spotlight,prices,related_uris,purchase_uris,mtgo_foil_id,power,toughness,flavor_text,edhrec_rank,penny_rank,printed_name,printed_type_line,printed_text,security_stamp,promo_types,loyalty,watermark,frame_effects,card_faces,preview,resource_id,color_indicator,tcgplayer_etched_id,content_warning,flavor_name,attraction_lights,variation_of,life_modifier,hand_modifier,defense
820,card,00622151-6852-43d3-b825-02b4a2c0cbd5,cc187110-1148-4090-bbb8-e205694a39f5,[],NaN,NaN,NaN,NaN,Counterspell,fr,1997-03-24,https://api.scryfall.com/cards/00622151-6852-43d3-b825-02b4a2c0cbd5,https://scryfall.com/card/5ed/77/fr/contresort-(counterspell)?utm_source=api,normal,False,placeholder,"{'small': 'https://cards.scryfall.io/small/front/0/0/00622151-6852-43d3-b825-02b4a2c0cbd5.jpg?1539776373', 'normal':...",{U}{U},2.0,Instant,Counter target spell.,[U],[U],[],NaN,NaN,"{'standard': 'not_legal', 'future': 'not_legal', 'historic': 'legal', 'timeless': 'legal', 'gladiator': 'legal', 'pi...",[paper],False,False,False,True,[nonfoil],False,False,True,False,5afd2f4b-8309-4f45-a2b2-3785018474cb,5ed,Fifth Edition,core,https://api.scryfall.com/sets/5afd2f4b-8309-4f45-a2b2-3785018474cb,https://api.scryfall.com/cards/search?order=set&q=e%3A5ed&unique=prints,https://scryfall.com/sets/5ed?utm_source=api,https://api.scryfall.com/cards/00622151-6852-43d3-b825-02b4a2c0cbd5/rulings,https://api.scryfall.com/cards/search?order=released&q=oracleid%3Acc187110-1148-4090-bbb8-e205694a39f5&unique=prints,77,False,common,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Hannibal King,[47fa68ed-4d79-4116-a562-fc0c11096e81],717edff6-c8e9-4dfd-9cc1-1128aee55915,white,1997,False,False,True,False,"{'usd': None, 'usd_foil': None, 'usd_etched': None, 'eur': None, 'eur_foil': None, 'tix': None}",{'tcgplayer_infinite_articles': 'https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer....,{'tcgplayer': 'https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2F...,NaN,NaN,NaN,NaN,16.0,8.0,Contresort,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1039,card,007ba9b8-49a5-4825-babb-0b01bc1afe10,cc187110-1148-4090-bbb8-e205694a39f5,[518069],NaN,NaN,NaN,NaN,Counterspell,ru,2021-04-23,https://api.scryfall.com/cards/007ba9b8-49a5-4825-babb-0b01bc1afe10,https://scryfall.com/card/sta/15/ru/%D0%BE%D1%82%D0%BC%D0%B5%D0%BD%D0%B0-%D0%B7%D0%B0%D0%BA%D0%BB%D0%B8%D0%BD%D0%B0%...,normal,False,lowres,"{'small': 'https://cards.scryfall.io/small/front/0/0/007ba9b8-49a5-4825-babb-0b01bc1afe10.jpg?1619494261', 'normal':...",{U}{U},2.0,Instant,Counter target spell.,[U],[U],[],NaN,NaN,"{'standard': 'not_legal', 'future': 'not_legal', 'historic': 'legal', 'timeless': 'legal', 'gladiator': 'legal', 'pi...","[arena, paper, mtgo]",False,False,True,True,"[nonfoil, foil, etched]",False,False,True,False,5064a720-907f-4cb6-a425-766dc1dd7374,sta,Strixhaven Mystical Archive,masterpiece,https://api.scryfall.com/sets/5064a720-907f-4cb6-a425-766dc1dd7374,https://api.scryfall.com/cards/search?order=set&q=e%3Asta&unique=prints,https://scryfall.com/sets/sta?utm_source=api,https://api.scryfall.com/cards/007ba9b8-49a5-4825-babb-0b01bc1afe10/rulings,https://api.scryfall.com/cards/search?order=released&q=oracleid%3Acc187110-1148-4090-bbb8-e205694a39f5&unique=prints,15,False,rare,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Olena Richards,[fad4282c-49d1-4b5b-be1d-713369fc8bc8],5fd63e8f-8782-42af-9b43-f4b91cd260cf,borderless,2015,False,False,False,False,"{'usd': None, 'usd_foil': None, 'usd_etched': None, 'eur': None, 'eur_foil': None, 'tix': None}","{'gatherer': 'https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=518069&printed=true', 'tcgplayer_inf...",{'tcgplayer': 'https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2F...,NaN,NaN,NaN,"«Чтобы подавить эффект заклинания, вовсе не обязательно знать принципы его работы. Достаточно поменять правила реаль...",16.0,8.0,Отмена Заклинания,Мгновенное заклинание,Отмените целевое заклинание.,oval,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3764,card,01ca20a9-4034-4dd8-875c-fa24928335b6,cc187110-1148-4090-bbb8-e205694a39f5,[518132],NaN,NaN,NaN,NaN,Counterspell,zhs,2021-04-23,https://api.scryfall.com/cards/01ca20a9-4034-4dd8-875c-fa24928335b6,https://scryfall.com/card/sta/15/zhs/%E5%8F%8D%E5%87%BB%E5%92%92%E8%AF%AD-(counterspell)?utm_source=api,normal,False,lowres,"{'small': 'https://cards.scryfall.io/small/front/0/1/01ca20a9-4034-4dd8-875c-fa24928335b6.jpg?1619494522', 'normal':...",{U}{U},2.0,Instant,Counter target spell.,[U],[U],[],NaN,NaN,"{'standard': 'not_legal', 'future': 'not_legal', 'historic': 'legal', 'timeless': 'legal', 'gladiator': 'legal', 'pi...","[arena, paper, mtgo]",False,False,True,True,"[nonfoil, foil, etched]",False,False,True,False,5064a720-907f-4cb6-a425-766dc1dd7374,sta,Strixhaven Mystical Archive,masterpiece,https://api.scryfall.com/sets/5064a720-907f-4cb6-a425-766dc1dd7374,https://api.scryfall.com/cards/search?order=set&q=e%3Asta&unique=prints,https://scryfall.com/sets/sta?utm_source=api,https://api.scryfall.com/cards/01ca20a9-4034-4dd8-875c-fa24928335b6/rulings,https://api.scryfall.com/cards/search?order=released&q=oracleid%3Acc187110-1148-4090-bbb8-e205694a39f5&unique=prints,15,False,rare,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Olena Richards,[fad4282c-49d1-4b5b-be1d-713369fc8bc8],5fd63e8f-8782-42af-9b43-f4b91cd260cf,borderless,2015,False,False,False,False,"{'usd': None, 'usd_foil': None, 'usd_etched': None, 'eur': None, 'eur_foil': None, 'tix': None}","{'gatherer': 'https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=518132&printed=true', 'tcgplayer_inf...",{'tcgplayer': 'https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2F...,NaN,NaN,NaN,「至于压制咒语效果的具体细节也不用去了解。只需重新整理咒语作用实界内的规则就可实现。」\n～量析院长英巴罕,16.0,8.0,反击咒语,瞬间,反击目标咒语。,oval,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5918,card,02da8709-4228-4fed-9d2d-781e686661df,cc187110-1148-4090-bbb8-e205694a39f5,[598919],107579.0,NaN,457501.0,688679.0,Counterspell,en,2023-01-13,https://api.scryfall.com/cards/02da8709-4228-4fed-9d2d-781e686661df,https://scryfall.com/card/dmr/45/counterspell?utm_source=api,normal,True,highres_scan,"{'small': 'https://cards.scryfall.io/small/front/0/2/02da8709-4228-4fed-9d2d-781e686661df.jpg?1675199223', 'normal':...",{U}{U},2.0,Instant,Counter target spell.,[U],[U],[],NaN,NaN,"{'standard': 'not_legal', 'future': 'not_legal', 'historic': 'legal', 'timeless': 'legal', 'gladiator': 'legal', 'pi...","[paper, mtgo]",False,False,True,True,"[nonfoil, foil]",False,False,True,False,ca4c2884-e539-4b7f-980d-5d6a50220f2a,dmr,Dominaria Remastered,masters,https://api.scryfall.com/sets/ca4c2884-e539-4b7f-980d-5d6a50220f2a,https://api.scryfall.com/cards/search?order=set&q=e%3Admr&unique=prints,https://scryfall.com/sets/dmr?utm_source=api,https://api.scryfall.com/cards/02da8709-4228-4fed-9d2d-781e686661df/rulings,https://api.scryfall.com/cards/search?order=released&q=oracleid%3Acc187110-1148-4090-bbb8-e205694a39f5&unique=prints,45,False,common,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Zack Stella,[17bc7f55-958b-43f4-bb40-09746d05b3f9],1044055e-a362-4edb-8101-96655e15da95,black,2015,False,False,True,False,"{'usd': '2.49', 'usd_foil': '3.15', 'usd_etched': None, 'eur': '2.48', 'eur_foil': '2.98', 'tix': '0.13'}","{'gatherer': 'https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=598919&printed=false', 'tcgplayer_in...",{'tcgplayer': 'https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2F...,NaN,NaN,NaN,NaN,16.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6445,card,031d2023-6410-441c-8444-92d3450cb5b9,cc187110-1148-4090-bbb8-e205694a39f5,[442537],NaN,NaN,NaN,NaN,Counterspell,zhs,2018-03-16,https://api.scryfall.com/cards/031d2023-6410-441c-8444-92d3450cb5b9,https://scryfall.com/card/a25/50/zhs/%E5%8F%8D%E5%87%BB%E5%92%92%E8%AF%AD-(counterspell)?utm_source=api,normal,False,lowres,"{'small': 'https://cards.scryfall.io/small/front/0/3/031d2023-6410-441c-8444-92d3450cb5b9.jpg?1562432291', 'normal':...",{U}{U},2.0,Instant,Counter target spell.,[U],[U],[],NaN,NaN,"{'standard': 'not_legal', 'future': 'not_legal', 'historic': 'legal', 'timeless': 'legal', 'gladiator': 'legal', 'pi...","[paper, mtgo]",False,False,True,True,"[nonfoil, foil]",False,False,True,False,41ee6e2f-69b3-4c53-8a8e-960f5e974cfc,a25,Masters 25,masters,https://api.scryfall.com/sets/41ee6e2f-69b3-4c53-8a8e-960f5e974cfc,https://api.scryfall.com/cards/search?order=set&q=e%3Aa25&unique=prints,https://scryfall.com/sets/a25?utm_source=api,https://api.scryfall.com/cards/031d2023-6410-441c-8444-92d3450cb5b9/rulings,https://api.scryfall.com/cards/search?order=released&q=oracleid%3Acc187110-1148-4090-bbb8-e205694a39f5&unique=prints,50,False,common,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Zack Stella,[17bc7f55-958b-43f4-bb40-09746d05b3f9],1044055e-a362-4edb-8101-96655e15da95,black,2015,False,False,True,False,"{'usd': None, 'usd_foil': None, 'usd_etched': None, 'eur': None, 'eur_foil': None, 'tix': None}","{'gatherer': 'https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=442537&printed=true', 'tcgplayer_inf...",{'tcgplayer': 'https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2F...,NaN,NaN,NaN,NaN,16.0,8.0,反击咒语,瞬间,反击目标咒语。,NaN,NaN,NaN,set,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
508667,card,f5c6f284-fc07-4849-8210-80f12f77f518,cc187110-1148-4090-bbb8-e205694a39f5,[502305],NaN,NaN,227054.0,512945.0,Counterspell,en,2020-11-20,https://api.scryfall.com/cards/f5c6f284-fc07-4849-8210-80f12f77f518,https://scryfall.com/card/cmr/632/counterspell?utm_source=api,normal,True,highres_scan,"{'small': 'https://cards.scryfall.io/small/front/f/5/f5c6f284-fc07-4849-8210-80f12f77f518.jpg?1608918439', 'normal':...",{U}{U},2.0,Instant,Counter target spell.,[U],[U],[],NaN,NaN,"{'standard': 'not_legal', 'future': 'not_legal', 'historic': 'legal', 'timeless': 'legal', 'gladiator': 'legal', 'pi...","[paper, mtgo]",False,False,True,True,"[nonfoil, foil]",False,False,True,False,39de6fbf-1f11-48d0-8f04-f0407f6a0732,cmr,Commander Legends,draft_innovation,https://api.scryfall.com/sets/39de6fbf-1f11-48d0-8f04-f0407f6a0732,https://api.scryfall.com/cards/search?order=set&q=e%3Acmr&unique=prints,https://scryfall.com/sets/cmr?utm_source=api,https://api.scryfall.com/cards/f5c6f284-fc07-4849-8210-80f12f77f518/rulings,https://api.scryfall.com/cards/search?order=released&q=oracleid%3Acc187110-1148-4090-bbb8-e205694a39f5&unique=prints,632,False,common,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Zack Stella,[17bc7f55-958b-43f4-bb40-09746d05b3f9],1044055e-a362-4edb-8101-96655e15da95,black,2015,False,False,False,False,"{'usd': '2.73', 'usd_foil': '3.60', 'usd_etched': None, 'eur': '2.52', 'eur_foil': '3.81', 'tix': None}","{'gatherer': 'https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=502305&printed=false', 'tcgplayer_in...",{'tcgplayer': 'https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2F...,NaN,NaN,NaN,NaN,16.0,8.0,NaN,NaN,NaN,oval,[boosterfun],NaN,NaN,[extendedart],NaN,"{'source': '3 Gordos Bastardos', 'source_uri': 'https://twitter.com/3ChubbyB/status/1323855244367835136', 'previewed...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
520633,card,fb85afd5-8c27-476f-afe1-606324c7399d,cc187110-1148-4090-bbb8-e205694a39f5,[601329],NaN,NaN,NaN,NaN,Counterspell,pt,2023-01-13,https://api.scryfall.com/cards/fb85afd5-8c27-476f-afe1-606324c7399d,https://scryfall.com/card/dmr/457/pt/contram%C3%A1gica-(counterspell)?utm_source=api,normal,False,lowres,"{'small': 'https://cards.scryfall.io/small/front/f/b/fb85afd5-8c27-476f-afe1-606324c7399d.jpg?1677137110', 'normal':...",{U}{U},2.0,Instant,Counter target spell.,[U],[U],[],NaN,NaN,"{'standard': 'not_legal', 'future': 'not_legal', 'historic': 'legal', 'timeless': 'legal', 'gladiator': 'legal', 'pi...",[paper],False,False,True,False,[foil],False,True,True,False,ca4c2884-e539-4b7f-980d-5d6a50220f2a,dmr,Dominaria Remastered,masters,https://api.scryfall.com/sets/ca4c2884-e539-4b7f-980d-5d6a50220f2a,https://api.scryfall.com/cards/search?order=set&q=e%3Admr&unique=prints,https://scryfall.com/sets/dmr?utm_source=api,https://api.scryfall.com/cards/fb85afd5-8c27-476f-afe1-606324c7399d/rulings,https://api.scryfall.com/cards/search?order=released&q=oracleid%3Acc187110-1148-4090-bbb8-e205694a39f5&unique=prints,457,False,rare,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Mark Poole,[bfdeaf09-f915-4058-8e8b-bcac3bc43c33],911ff9e4-cc26-4d32-a3ab-887d55af04c6,black,1997,False,False,False,False,"{'usd': None, 'usd_foil': None, 'usd_etched': None, 'eur': None, 'eur_foil': None, 'tix': None}","{'gatherer': 'https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=601329&printed=true', 'tcgplayer_inf...",{'tcgplayer': 'https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2F...,NaN,NaN,NaN,NaN,16.0,8.0,Contramágica,Mágica Instantânea,Anule a mágica alvo.,NaN,[release],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
521463,card,fbe63040-b69b-4494-81cb-7f099c0ca23c,cc187110-1148-4090-bbb8-e205694a39f5,[],NaN,NaN,NaN,NaN,Counterspell,fr,1997-10-14,https://api.scryfall.com/cards/fbe63040-b69b-4494-81cb-7f099c0ca23c,https://scryfall.com/card/tmp/57/fr/contresort-(counterspell)?utm_source=api,normal,False,placeholder,"{'small': 'https://cards.scryfall.io/small/front/f/b/fbe63040-b69b-4494-81cb-7f099c0ca23c.jpg?1539701305', 'normal':...",{U}{U},2.0,Instant,Counter target spell.,[U],[U],[],NaN,NaN,"{'standard': 'not_legal', 'future': 'not_legal', 'historic': 'legal', 'timeless': 'legal', 'gladiator': 'legal', 'pi...","[paper, mtgo]",False,False,False,True,[nonfoil],False,False,True,False,10df3a67-178e-4363-8668-34f0e6edf2a7,tmp,Tempest,expansion,https://api.scryfall.com/sets/10df3a67-178e-4363-8668-34f0e6edf2a7,https://api.scryfall.com/cards/search?order=set&q=e%3Atmp&unique=prints,https://scryfall.com/sets/tmp?utm_source=api,https://api.scryfall.com/cards/fbe63040-b69b-4494-81cb-7f099c0ca23c/rulings,https://api.scryfall.com/cards/search?order=released&q=oracleid%3Acc187110-1148-4090-bbb8-e205694a39f5&unique=prints,57,False,common,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Stephen Daniele,[a267f9bb-072b-410a-a704-50f4d19020d8],02602346-cc8d-429d-bc6e-3a6495067172,black,1997,False,False,True,False,"{'usd': None, 'usd_foil': None, 'usd_etched': None, 'eur': None, 'eur_foil': None, 'tix': None}",{'tcgplayer_infinite_articles': 'https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&trafcat=tcgplayer....,{'tcgplayer': 'https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2F...,NaN,NaN,NaN,NaN,16.0,8.0,Contresort,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
528628,card,ff59891b-a309-4b10-bec6-f63bfe281d85,cc187110-1148-4090-bbb8-e205694a39f5,[622890],NaN,NaN,NaN,NaN,Counterspell,de,2023-08-04,https://api.scryfall.com/cards/ff59891b-a309-4b10-bec6-f63bfe281d85,https://scryfall.com/card/cmm/81/de/gegenzauber-(counterspell)?utm_source=api,normal,False,lowres,"{'small': 'https://cards.scryfall.io/small/front/f/f/ff59891b-a309-4b10-bec6-f63bfe281d85.jpg?1734849157', 'normal':...",{U}{U},2.0,Instant,Counter target spell.,[U],[U],[],NaN,NaN,"{'standard': 'not_legal', 'future': 'not_legal', 'historic': 'legal', 'timeless': 'legal', 'gladiator': 'legal', 'pi...","[paper, mtgo]",False,False,True,True,"[nonfoil, foil]",False,False,True,False,cd05036f-2698-43e6-a48e-5c8d82f0a551,cmm,Commander Masters,masters,https://api.scryfall.com/sets/cd05036f-2698-43e6-a48e-5c8d82f0a551,https://api.scryfall.com/cards/search?order=set&q=e%3Acmm&unique=prints,https://scryfall.com/sets/cmm?utm_source=api,https://api.scryfall.com/cards/ff59891b-a309-4b10-bec6-f63bfe281d85/rulings,https://api.scryfall.com/cards/search?order=released&q=oracleid%3Acc187110-1148-4090-bbb8-e205694a39f5&unique=prints,81,False,common,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Jason Chan,[8062d5a9-51b6-4822-933f-fa9e9dba8416],32026e72-0882-4ce4-a3a7-ef58d43804e7,black,2015,False,False,True,False,"{'usd': None, 'usd_foil': None, 'usd_etched': None, 'eur': None, 'eur_foil': None, 'tix': None}","{'gatherer': 'https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=622890&printed=true', 'tcgplayer_inf...",{'tcgplayer': 'https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2F...,NaN,NaN,NaN,Die Pyromagierin beschwor ihren mächtigsten Sturm aus Zorn und Feuer. Jace täuschte Interesse vor.,16.0,8.0,Gegenzauber,Spontanzauber,Neutralisiere einen Zauberspruch deiner Wahl.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
529690,card,ffdf9d2a-c163-43df-9a2f-20b8749c86ae,cc187110-1148-4090-bbb8-e205694a39f5,[517565],89087.0,77494.0,235162.0,556418.0,Counterspell,en,2021-04-23,https://api.scryfall.com/cards/ffdf9d2a-c163-43df-9a2f-20b8749c86ae,https://scryfall.com/card/sta/15/counterspell?utm_source=api,normal,True,highres_scan,"{'small': 'https://cards.scryfall.io/small/front/f/f/ffdf9d2a-c163-43df-9a2f-20b8749c86ae.jpg?1631491044', 'normal':...",{U}{U},2.0,Instant,Counter target spell.,[U],[U],[],NaN,NaN,"{'standard': 'not_legal', 'future': 'not_legal', 'historic': 'legal', 'timeless': 'legal', 'gladiator': 'legal', 'pi...","[arena, paper, mtgo]",False,False,True,True,"[nonfoil, foil, etched]",False,False,True,False,5064a720-907f-4cb6-a425-766dc1dd7374,sta,Strixhaven Mystical Archive,masterpiece,https://api.scryfall.com/sets/5064a720-907f-4cb6-a425-766dc1dd7374,https://api.scryfall.com/cards/search?order=set&q=e%3Asta&unique=prints,https://scryfall.com/sets/sta?utm_source=api,https://api.scryfall.com/cards/ffdf9d2a-c163-43df-9a2f-20b8749c86ae/rulings,https://api.scryfall.com/cards/search?order=released&q=oracleid%3Acc187110-1148-4090-bbb8-e205694a39f5&unique=prints,15,False,rare,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Olena Richards,[fad4282c-49d1-4b5b-be1d-713369fc8bc8],5fd63e8f-8782-42af-9b43-f4b91cd260cf,borderless,2015,False,False,False,False,"{'usd': '6.95', 'usd_foil': '10.89', 'usd_etched': '10.53', 'eur': '4.48', 'eur_foil': '9.27', 'tix': '0.33'}","{'gatherer': 'https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=517565&printed=false', 'tcgplayer_in...",{'tcgplayer': 'https://partner.tcgplayer.com/c/4931599/1830156/21018?subId1=api&u=https%3A%2F%2Fwww.tcgplayer.com%2F...,NaN,NaN,NaN,"""One need not know the specific details of a spell to suppress its effect. Simply rearrange the rules of the reality...",16.0,8.0,NaN,NaN,NaN,oval,NaN,NaN,NaN,[showcase],NaN,"{'source': 'Wizards of the Coast', 'source_uri': 'https://www.twitch.tv/videos/962617661', 'previewed_at': '2021-03-...",NaN,NaN,235163.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
cards_raw['object'].value_counts()

object
card    529942
Name: count, dtype: int64

In [8]:
key_cols = ["id", "oracle_id", "name"]
for col in key_cols:
    print(f"{col}: {cards_raw[col].nunique():,} unique values")

id: 529,942 unique values
oracle_id: 37,400 unique values
name: 36,983 unique values

In [11]:
problem_cols = []

for col in cards_raw.columns:
    has_unhashable = cards_raw[col].apply(
        lambda x: isinstance(x, (list, dict, set, np.ndarray))
    ).any()
    
    if has_unhashable:
        problem_cols.append(col)

problem_cols

['multiverse_ids',
 'image_uris',
 'colors',
 'color_identity',
 'keywords',
 'produced_mana',
 'all_parts',
 'legalities',
 'games',
 'finishes',
 'artist_ids',
 'prices',
 'related_uris',
 'purchase_uris',
 'promo_types',
 'frame_effects',
 'card_faces',
 'preview',
 'color_indicator',
 'attraction_lights']

In [9]:
# Drop:
    # object
# Common to all:
    # id
    # oracle_id
    # name
# All Links & IDs
    # multiverse_ids
    # mtgo_id
    # arena_id
    # tcgplayer_id
    # cardmarket_id
    # mtgo_foil_id
    # tcgplayer_etched_id
    # card_back_id
    # illustration_id
    # resource_id
    # uri
    # scryfall_uri
    # image_uris
    # set_uri
    # set_search_uri
    # scryfall_set_uri
    # rulings_uri
    # prints_search_uri
    # purchase_uris
    # related_uris
    # variation_of
# Game Features
    # mana_cost
    # cmc
    # type_line
    # oracle_text
    # colors
    # color_identity
    # color_indicator
    # keywords
    # produced_mana
    # game_changer
    # rarity
    # power
    # toughness
    # loyalty
    # defense
    # attraction_lights
    # card_faces
    # all_parts
    # legalities
    # games
    # rulings_uri
# Every Printing
    # released_at
    # lang
    # prices
    # highres_image
    # image_status
    # reserved
    # foil
    # nonfoil
    # finishes
    # oversized
    # promo
    # reprint
    # variation
    # set_id
    # set
    # set_name
    # set_type
    # collector_number
    # digital
    # card_back_id
    # artist
    # artist_ids
    # illustration_id
    # border_color
    # frame
    # full_art
    # textless
    # layout
    # booster
    # story_spotlight
    # prints_search_uri
    # tcgplayer_etched_id
    # flavor_text
    # purchase_uris
    # printed_name
    # printed_type_line
    # printed_text
    # security_stamp
    # promo_types
    # watermark
    # frame_effects
    # preview
    # variation_of
    # content_warning
    # flavor_name
# Misc
    # edhrec_rank
    # penny_rank
    # life_modifier
    # hand_modifier